# Generated by Django 4.0.6 on 2022-08-08 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_publisher_book_publisher'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='logo',
            field=models.ImageField(null=True, upload_to='publisher-logo'),
        ),
    ]
